apiVersion: v2
appVersion: "0.1.0"
name: suse-manager-proxy
description: Proxy for the Rancher SUSE Manager UI Extension
type: application
version: 0.1.0
#icon: https://raw.githubusercontent.com/rancher/ui-plugin-examples/main/pkg/extension-crd/icon.svg