apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managers.susemanager.cattle.io
spec:
  group: susemanager.cattle.io
  scope: Namespaced
  names:
    plural: managers
    singular: manager
    kind: Manager
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              displayName:
                type: string
              url:
                type: string
              username:
                type: string
              passwordSecret:
                type: string
              insecure:
                type: boolean
    additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: Display Name
      type: string
    - jsonPath: .spec.url
      name: URL
      type: string
    - jsonPath: .spec.username
      name: Username
      type: string
